# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [2]:
import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running (as each library, you can use np.__version__)
print(np.__version__)


2.1.2


In [3]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])
array1 = np.array([0.8, 0.6, 0.4])
print(array1)

[0.8 0.6 0.4]


In [10]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])

def random_array(interv_min, interv_max, nbre_alea):
    return np.random.random(nbre_alea) * (interv_max - interv_min) + interv_min

interv_min, interv_max, nbre_alea = 0.25, 1, 10

print(random_array(interv_min, interv_max, nbre_alea))

[0.90483425 0.43693478 0.42264331 0.46327091 0.49058619 0.63104629
 0.44799991 0.66681332 0.54469124 0.73330106]


In [19]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here
n, m = 5, 10
empty_array = np.empty(n)
print("empty_array =", empty_array)
print("type of empty_array =", type(empty_array))
# np.empty() crée un tableau sans initialiser ses valeurs. 
# Le tableau contient donc des valeurs arbitraires
# Allocation de mémoire pour remplir le tableau plus tard

empty_array = [ 1.    2.75  6.   10.75 17.  ]
type of empty_array = <class 'numpy.ndarray'>


In [22]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.
n, m = 10, 5
zero_array2 = np.zeros(n)
print(zero_array2)
print(type(zero_array2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [21]:
# Mission 6 : Create an array filled with 10 random integers.
n, m = 10, 10
random_integers1 = np.random.randint(0, 100, n)  # 10 entiers aléatoires entre 0 et 99
print(random_integers1)

[33 72 55 75 99  2 32 69 62 32]


In [23]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
n, m = 50, 100
random_choice_array = np.random.choice([0, 1, 2, 3, 4, 5, 6, 7], size=n)
print(random_choice_array)

[0 2 5 6 0 7 1 5 0 1 2 4 2 7 6 0 3 3 5 3 0 2 0 1 1 1 0 5 2 5 0 0 1 4 6 7 2
 2 5 5 3 7 0 4 1 0 3 6 4 0]
